dimensions:
  status:
    non_cadre:
      label_fr: "Non-cadre"
      label_en: "Non-executive"
      situation:
        salarié . contrat . statut cadre: "non"

    cadre:
      label_fr: "Cadre"
      label_en: "Executive"
      situation:
        salarié . contrat . statut cadre: "oui"

  territory:
    standard:
      label_fr: "Hors Alsace-Moselle"
      label_en: "Outside Alsace-Moselle"
      situation:
        salarié . régimes spécifiques . alsace moselle: "non"

    alsace_moselle:
      label_fr: "Alsace-Moselle"
      label_en: "Alsace-Moselle"
      situation:
        salarié . régimes spécifiques . alsace moselle: "oui"

  atmp:
    standard:
      label_fr: "AT/MP standard"
      label_en: "Standard AT/MP"
      situation: {}

    atmp_1:
      label_fr: "AT/MP 1 %"
      label_en: "AT/MP 1%"
      situation:
        établissement . taux ATMP: 1

    atmp_4:
      label_fr: "AT/MP 4 %"
      label_en: "AT/MP 4%"
      situation:
        établissement . taux ATMP: 4

    fonctions_support:
      label_fr: "Fonctions support"
      label_en: "Support functions"
      situation:
        salarié . cotisations . ATMP . taux fonctions support: "oui"

  firm_size:
    lt50:
      label_fr: "Moins de 50 salariés"
      label_en: "Fewer than 50 employees"
      situation: {}

    ge50:
      label_fr: "50 salariés et plus"
      label_en: "50 employees or more"
      situation: {}

  working_time:
    full_time:
      label_fr: "Temps plein"
      label_en: "Full-time"
      working_time_rate: 1.0
      situation:
        salarié . contrat . temps de travail . quotité:
          valeur: 100
          unité: "%"

    part_time_80:
      label_fr: "80 %"
      label_en: "80%"
      working_time_rate: 0.8
      situation:
        salarié . contrat . temps de travail . quotité:
          valeur: 80
          unité: "%"

    part_time_50:
      label_fr: "50 %"
      label_en: "50%"
      working_time_rate: 0.5
      situation:
        salarié . contrat . temps de travail . quotité:
          valeur: 50
          unité: "%"